XML:
- changed-files:
  - any-glob-to-any-file:
    - .xml/**

python:
- changed-files:
  - any-glob-to-any-file:
    - .py/**

documentation:
- changed-files:
  - any-glob-to-any-file:
    - .github/**
    - README.md**
    - LICENSE**

PNG:
- changed-files:
  - any-glob-to-any-file:
    - .png/**